### ISSUE TITLE
GitHub doesn't link properly local file references from Org files.

### ISSUE THREAD

**Issue by alejandrosame** [GregDavidson/computing-magic#2]
If we want to provide learners with proper navigation on the GitHub frontend, we need a solution/workaround to this problem. 

## Example of problematic link
```
- Here's a [[file://Reference-Sheets/bash-metas.pdf][handy reference sheet]] on such
``` 
Line 200 at [shell-scripting-resilience.org/e6843a4868b93ddd6190d8bbab72148f8c3fa314](https://raw.githubusercontent.com/GregDavidson/computing-magic/e6843a4868b93ddd6190d8bbab72148f8c3fa314/Scripting/shell-script-resilience.org)

**Comment by GregDavidson** [comment]
Thanks, fixed!
